name: m4ush3r-action

on:
  push:

jobs:
  run_api_test:
    runs-on: ubuntu-latest
    name: Execute RapidAPI API Tests
    
    steps:
    - name: Execute Tests
      id: tstExec
      uses: m4ush3r/rapidapi-node14@v2
      with:
        test: 'test_310a6230-95a8-4753-902c-90637fbc5ba8'
        location: 'AWS-EU-WEST-3'
        environment: 'environment_23ac1850-3ffa-466a-9314-b93a2a81cd6a'
    
    - name: Show Results
      run: echo "The test took ${{ steps.tstExec.outputs.time }}ms to run"; echo "The test result was ${{ steps.tstExec.outputs.computedStatus }}"; echo "View Report - ${{ steps.tstExec.outputs.reportUrl }}"
